app = "white-wave-7991"
primary_region = "ams"

[build.args]
PB_VERSION = "0.19.0"
APP_URL = "https://hermanngmeiner.edu.al"

[http_service]
auto_start_machines = true
auto_stop_machines = false
force_https = true
internal_port = 8_080
min_machines_running = 1
processes = [ "app" ]

[http_service.concurrency]
hard_limit = 550
soft_limit = 500
type = "requests"

[[mounts]]
destination = "/pb/pb_data"
source = "pb_data"